# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-21 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_reads_app', '0004_auto_20190621_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='book',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
