# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-17 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0002_auto_20190617_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
